### ISSUE TITLE
README ideas - comparisons to overlapping projects

### ISSUE THREAD

**Issue by shanesveller** [gramos/panthro#2]
Hi there - not trying to rain on your parade, I'd love to see details from how this project differs from something like [Geminabox's proxying support](https://github.com/geminabox/geminabox#rubygems-proxy) or a caching reverse proxy like [Squid](http://www.squid-cache.org/), in both current and planned features. Alternately, if this is written mostly as a learning exercise, it might be good to say so as well.

**Comment by gramos** [comment]
Hi, it was written as learning exercise. And is not the same as gem in a box. Probaly squid can do the same thing. Ill write a compare post in my blog. Thnaks

**Comment by gramos** [comment]
https://github.com/gramos/panthro/commit/a891839c70d4ed71b09c3eace512e1c39ea7eaf2
